### ISSUE TITLE
api任务管理接口无法调用 pages/server/api/add_task

### ISSUE THREAD

**Issue by nifiii** [TarsCloud/TarsWeb#12]
### api任务管理接口无法调用 pages/server/api/add_task
**tars版本1.6.0**
**api.md文档格式重启应用，请求数据如下：**
{
    "serial": "true",
    "items": [{
        "server_id": "upiao.configSvr_10.105.232.120",  
        "command": "restart",
        "parameters": {}
    }]
}

**返回如下报错：**
{
  "data": {},
  "ret_code": 500,
  "err_msg": "系统内部错误"
}

**Comment by JSFiend** [comment]
在 log 文件夹下搜索下 [TaskController.addTask]:  看看是什么原因报错

**Comment by JSFiend** [comment]
"server_id": "upiao.configSvr_10.105.232.120",

server_id 应该是服务的 id， 不是服务名。
