### ISSUE TITLE
api/server_list?tree_node_id=   用token也提示  未登录

### ISSUE THREAD

**Issue by BaBahsq** [TarsCloud/TarsWeb#124]
api/server_list?tree_node_id=0     用token也提示  未登录

**Comment by ruanshudong** [comment]
ticket=, 应该是这个参数吧?

**Comment by BaBahsq** [comment]
已解决了，url中多个参数中间用&amp;而不是？&nbsp;




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 晚上8:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TarsCloud/TarsWeb] api/server_list?tree_node_id=   用token也提示  未登录 (#124)





 
ticket=, 应该是这个参数吧?

**Comment by BaBahsq** [comment]
已解决了，url中多个参数之间使用&amp;,而不是？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TarsCloud/TarsWeb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TarsCloud/TarsWeb] api/server_list?tree_node_id=   用token也提示  未登录 (#124)





 
ticket=, 应该是这个参数吧?
