### ISSUE TITLE
能否提供SET区域级批量发布功能？

### ISSUE THREAD

**Issue by lanyutc** [TarsCloud/TarsWeb#13]
举个例子一个app：testapp
对用户进行了set划分：
hubei.wuhan.1，hubei.wuhan.2，……，hubei.wuhan.30
shanghai.minhang.1，shanghai.minhang.2，……，shanghai.minhang.30
每个set下面都有一个Server：testServer

-------------------
每次发布testServer的时候，都得点入对应的set名下的Server进行发布，一共发布30+30=60次，能否提供直接在SET区域（例子中的wuhan，minhang）层级的批量发布功能？

**Comment by lanyutc** [comment]
自己造个轮子：https://github.com/lanyutc/TarsBatchPatch

**Comment by JSFiend** [comment]
暂不支持批量发布哈

**Comment by JSFiend** [comment]
后面会考虑批量发布哈
