### ISSUE TITLE
怎么部署啊？

### ISSUE THREAD

**Issue by antiWalker** [TarsCloud/TarsWeb#15]
怎么部署在linux上啊？都没有文档。

**Comment by antiWalker** [comment]
how wo deploy in linux?where is the fucking doc?

**Comment by JSFiend** [comment]
https://github.com/TarsCloud/Tars/blob/master/Install.zh.md#chapter-4   

web 依赖 tars 框架， 在安装 tars 框架的时候， 会有 web 的部署教程
