### ISSUE TITLE
master版本网关配置-站点配置-新增路由点击报错

### ISSUE THREAD

**Issue by Du-Ki** [TarsCloud/TarsWeb#152]
![A@M42W@RJZ29W8)NP)HH204](https://user-images.githubusercontent.com/52734438/142157134-b1a40d55-155f-462e-b42d-ab1b86371655.png)
网关配置-站点配置-新增路由，点击后报错，并且无法加载数据
![O6$YT@C~(CZYA EJ@KCP~C4](https://user-images.githubusercontent.com/52734438/142157162-17e22d4a-b577-4918-b671-4b8eb9b7c395.png)
可能问题点定位
![$WRN~BUMVY54CQE$TT~AYWW](https://user-images.githubusercontent.com/52734438/142157247-963463de-f36f-47a1-af11-c35d71535afe.png)
源码位置
![3DUKJN}}H8@C_4WL$~ C1_3](https://user-images.githubusercontent.com/52734438/142157272-66014836-a804-4dfd-87b7-25a3e8af206d.png)

**Comment by zouchengzhuo** [comment]
能否提供一下tarsweb版本？ 在右上角可查看

**Comment by Du-Ki** [comment]
> 能否提供一下tarsweb版本？ 在右上角可查看

![image](https://user-images.githubusercontent.com/52734438/142160862-1d70a969-540c-43b9-8c48-e690627272a8.png)

**Comment by zouchengzhuo** [comment]
> > 能否提供一下tarsweb版本？ 在右上角可查看
> 
> ![image](https://user-images.githubusercontent.com/52734438/142160862-1d70a969-540c-43b9-8c48-e690627272a8.png)

最新的master和release分支中已修复
