### ISSUE TITLE
improve web:2.4.20 应用部署功能改进建议

### ISSUE THREAD

**Issue by Du-Ki** [TarsCloud/TarsWeb#165]
关于tarsweb的部署申请，部署应用名称的输入，应该可以优化一下，增加一个应用名称检测或者输入框可实现多次输入覆写value。

在申请部署中，应用输入框直接输入一个不存在的应用时候会正常进行提示通知。
![H`PYUZE)06(2@CMUV1$T_T6](https://user-images.githubusercontent.com/52734438/145137429-b0eaacc5-ef7e-4378-8070-335e9450fa1e.png)

但是在我选择了一个现有的应用之后，再次输入一个不存在的应用，却能完成部署申请。
![{BOY`A@_VF(D}Z7F5L)Q MU](https://user-images.githubusercontent.com/52734438/145137431-b0fc2040-ce8c-44f8-92fb-4bdcf8097f1d.png)
![W8E _5%)E4JRP7G4J6HDLRC](https://user-images.githubusercontent.com/52734438/145137430-a199e5b0-e430-4936-917b-4da0a43153f6.png)
![N6O (8EF)QPPIDF%N89WXD](https://user-images.githubusercontent.com/52734438/145137428-48ad773e-9b0c-4006-ad89-7ad8f0607a90.png)

此种操作虽然完成了部署，但却是部署在了应用名test下，而不是test2，并不是预期结果，会产生较大的误导性。对于不熟悉tarsweb操作的新手来说，可能会比较不友好。

**Comment by ruanshudong** [comment]
fix
