### ISSUE TITLE
addToken error

### ISSUE THREAD

**Issue by logtous** [TarsCloud/TarsWeb#168]
![image](https://user-images.githubusercontent.com/88697234/150263390-efe17ef9-ad89-4c07-8b96-41990ae60569.png)

https://github.com/TarsCloud/TarsWeb/blob/f33e831f8968911882ae87ae09ec8b50dd3238f6/sso/dao/db/db_user_system_models/t_token.js#L16
![image](https://user-images.githubusercontent.com/88697234/150263337-2aec81a6-6ec6-47aa-902f-2215c6388f84.png)

![image](https://user-images.githubusercontent.com/88697234/150263281-9e6c7921-e189-4daa-8595-f8e2b7793035.png)

**Comment by ruanshudong** [comment]
啥意思? 被截断了?

**Comment by logtous** [comment]
@ruanshudong 数据库表字段长度时128，实际生成的token时大于128的，所以保存失败了。fix pr: https://github.com/TarsCloud/TarsWeb/pull/169
