### ISSUE TITLE
server/api/task 接口能否返回更详细的错误信息?

### ISSUE THREAD

**Issue by jiaxingzack** [TarsCloud/TarsWeb#19]
[server/api/task](https://github.com/TarsCloud/TarsWeb/blob/master/docs/api.md#serverapitask) 如果出现错误时能否返回更详细的错误信息或错误码? 

status_info 仅仅返回 EM_I_FAILED 和 EM_I_SUCCESS 参考意义不大.

**Comment by ziyang314** [comment]
还会返回execute_info等信息
