### ISSUE TITLE
如何让同一个服务部署在两台机器上？

### ISSUE THREAD

**Issue by antiWalker** [TarsCloud/TarsWeb#21]
你好，我有两台机器，226和229
然后我开发了一个helloworld的服务，已经通过226上的web管理平台（ http://172.18.12.226:3000/index.html  ）部署在226上了。我想把这个服务部署在229上怎么部署？是不是要在229的web管理平台上上传然后部署？我能否直接在226的web管理平台上部署成功？困扰我。
<img width="2330" alt="图片" src="https://user-images.githubusercontent.com/27910878/59738403-ba99cc00-9293-11e9-9895-887b3ba6258b.png">

**Comment by JSFiend** [comment]
通过扩容， 再发布就好

**Comment by antiWalker** [comment]
> 通过扩容， 再发布就好

<img width="873" alt="图片" src="https://user-images.githubusercontent.com/27910878/59767041-0bc9b000-92d4-11e9-8040-edde9125380b.png">
先扩容了。再发布还是不行啊。。。。
