### ISSUE TITLE
安装tarsweb必须还要装TarsFramework吗？

### ISSUE THREAD

**Issue by Barber0** [TarsCloud/TarsWeb#25]
我尝试仅创建了所需的数据库，并通过npm安装了tarsWeb管理系统，然后发布tars-go写的应用，出现报错。

[TARS][EndpointManager doEndpoints, exception ,return: -13001  ,objname: tars.tarsAdminRegistry.AdminRegObj  ,setname:

**Comment by ziyang314** [comment]
只安装tars-web肯定不行的。
