### ISSUE TITLE
模板管理无法显示，需要修改TemplateDao.js

### ISSUE THREAD

**Issue by qiuxin** [TarsCloud/TarsWeb#27]
问题现象：tarsweb在点击“运维管理”---》“模板管理”的情况下，会弹出系统错误对话框，模板管理无法显示。经定位发现是：  /TarsWeb/app/dao文件件下TemplateDao.js需要修改，具体修改之后的文件见如下：

[root@VM_0_13_centos dao]# cat TemplateDao.js
/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

const {tProfileTemplate} = require('./db').db_tars;
const Sequelize = require('sequelize');

const TemplateDao = {};

TemplateDao.addTemplate = async (params) => {
	return await tProfileTemplate.create({
		template_name: params.templateName,
		parents_name: params.parentsName,
		profile: params.profile,
		posttime: params.posttime,
		lastuser: params.lastUser
	});
};

TemplateDao.deleteTemplate = async (id) => {
	return await tProfileTemplate.destroy({
		where: {
			id: id
		}
	});
};

TemplateDao.updateTemplate = async (params) => {
	return await tProfileTemplate.update({
		template_name: params.template_name,
		parents_name: params.parents_name,
		profile: params.profile,
		posttime: params.posttime,
	}, {
		where: {
			id: params.id
		}
	});
};

TemplateDao.getTemplateById = async (id) => {
	return await tProfileTemplate.findOne({
		where: {
			id
		}
	});
};

TemplateDao.getTemplateByName = async (templateName) => {
	return await tProfileTemplate.findOne({
		where: {
			template_name: templateName
		}
	});
};

TemplateDao.getTemplateList = async (templateName, parentsName) => {
        const Op=Sequelize.Op;
	return await tProfileTemplate.findAll({
		where: {
			template_name: {
			//	$like: '%' + templateName + '%'
			    [Op.like]: `%${templateName}%`
			},
			parents_name: {
			//	$like: '%' + parentsName + '%'
			    [Op.like]: `%${parentsName}%`
			}
		}
	});
};

module.exports = TemplateDao;
[root@VM_0_13_centos dao]#

**Comment by BrrayLi** [comment]
根据tars手动安装文档后，“运维管理”下“模板管理”菜单打开会有如下图报错，其他与模板相关的地方下拉菜单均无法选择。


使用pm2 logs tars-node-web查看日志有如下记录，请有缘人提供解决方法。

0|tars-node-web  | error: 192.168.2.10|admin|TemplateController.js:83|[getTemplateList] Error: Invalid value { '$like': '%%' }
0|tars-node-web  |     at Object.escape (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/sql-string.js:65:11)
0|tars-node-web  |     at MySQLQueryGenerator.escape (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:963:22)
0|tars-node-web  |     at MySQLQueryGenerator._whereParseSingleValueObject (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2423:41)
0|tars-node-web  |     at MySQLQueryGenerator.whereItemQuery (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2141:19)
0|tars-node-web  |     at Utils.getComplexKeys.forEach.prop (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2044:25)
0|tars-node-web  |     at Array.forEach (<anonymous>)
0|tars-node-web  |     at MySQLQueryGenerator.whereItemsQuery (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2042:35)
0|tars-node-web  |     at MySQLQueryGenerator.getWhereConditions (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2444:19)
0|tars-node-web  |     at MySQLQueryGenerator.selectQuery (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1275:28)
0|tars-node-web  |     at QueryInterface.select (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/query-interface.js:1104:27)
0|tars-node-web  |     at Promise.try.then.then.then (/usr/local/app/tars/TarsWeb/node_modules/sequelize/lib/model.js:1751:34)
0|tars-node-web  |     at tryCatcher (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/util.js:16:23)
0|tars-node-web  |     at Promise._settlePromiseFromHandler (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/promise.js:512:31)
0|tars-node-web  |     at Promise._settlePromise (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/promise.js:569:18)
0|tars-node-web  |     at Promise._settlePromise0 (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/promise.js:614:10)
0|tars-node-web  |     at Promise._settlePromises (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/promise.js:694:18)
0|tars-node-web  |     at _drainQueueStep (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/async.js:138:12)
0|tars-node-web  |     at _drainQueue (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/async.js:131:9)
0|tars-node-web  |     at Async._drainQueues (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/async.js:147:5)
0|tars-node-web  |     at Immediate.Async.drainQueues (/usr/local/app/tars/TarsWeb/node_modules/bluebird/js/release/async.js:17:14)
0|tars-node-web  |     at runCallback (timers.js:810:20)
0|tars-node-web  |     at tryOnImmediate (timers.js:768:5)

**Comment by ziyang314** [comment]
升级了sequelize后没有测试充分，已回滚
