### ISSUE TITLE
启动demo中的用户系统，登录成功之后跳回不到tarsweb

### ISSUE THREAD

**Issue by hilberthu** [TarsCloud/TarsWeb#33]
![QQ图片20191015151127](https://user-images.githubusercontent.com/5734402/66808556-16ccde00-ef5e-11e9-9276-601f31015d59.png)
![微信图片_20191015151212](https://user-images.githubusercontent.com/5734402/66808616-3106bc00-ef5e-11e9-98fd-51bcc7afb93e.png)

**Comment by ETZhangSX** [comment]
demo中相关登录接口接受的默认重定向地址参数名为`redirect_url`，不是`service`，因此需要将`TarsWeb/config/loginConf.js`中的参数`redirectUrlParamName`改为`redirect_url`，才能完成页面的跳转。

同时需要修改`cookieDomain`为自己的服务器的域名(本地的话可以使用默认值`localhost`)，否则会由于无法在前端保存对应的cookie，重复重定向到登录页无法登录。

希望以上信息对你有帮助

**Comment by hilberthu** [comment]
谢谢，就是这样解决的，已经ok
