### ISSUE TITLE
jenkins 调用 api/upload_patch_package 返回 需要登录

### ISSUE THREAD

**Issue by desand** [TarsCloud/TarsWeb#42]
参考例子： https://github.com/TarsCloud/TarsDocs/blob/master/kai-fa/tarsphp/yu-laravel-jie-he-shi-yong.md

执行到：

> echo "上传build包"
> def packageDeploy = sh(script: "head -n 1 tmp.log", returnStdout: true).trim()
> sh "curl -H 'Host:172.18.0.3:3000' -F 'suse=@./${packageDeploy}' -F 'application=${APP_NAME}' -F 'module_name=${SERVER_NAME}' -F 'comment=${env.TAG_DESC}' http://172.18.0.3:3000/pages/server/api/upload_patch_package > curl.log"
（Host:172.18.0.3:3000 我已经改为自己的 tars 服务器地址）

读取 curl.log 返回
+ cat curl.log
{"ret_code":500,"err_msg":"您还没有登录","data":{}}

请问如何添加登录信息？

**Comment by ruanshudong** [comment]
意思是放开登录对吧?

**Comment by ruanshudong** [comment]
暂时通过web/webConf.js里面的参数uploadLogin来控制, 设置成false, 即可上传包不用登陆了.
暂时先解决你的问题, 这个方式未来可能会变, 从开发, 打包, 上传, 发布, 整个链条应该需要有一个统一的方式, 还没时间去折腾.

**Comment by desand** [comment]
> 从开发, 打包, 上传, 发布, 整个链条应该需要有一个统一的方式, 还没时间去折腾.

thx~

**Comment by virtualmemorys** [comment]
//上传文件不需要登录
if(WebConf.webConf.uploadLogin || process.env.TARS_WEB_UPLOAD == 'true')** {
	loginConf.ignore.push('/pages/server/api/upload_patch_package');
	loginConf.ignore.push('/api/upload_patch_package');
	loginConf.ignore.push('/pages/server/api/upload_and_publish');
	loginConf.ignore.push('/api/upload_and_publish');
}
 @ruanshudong 这个逻辑是不是写反了？？

**Comment by auqf** [comment]
you can use the token
