### ISSUE TITLE
非tars的微服务没有记录重启&&停止的日志信息

### ISSUE THREAD

**Issue by jianhuihi** [TarsCloud/TarsWeb#5]
非tars的服务没有记录重启&&停止的日志信息，期望加上

![image](https://user-images.githubusercontent.com/4176545/48989802-d4908780-f166-11e8-909a-c16b9cbf43b4.png)

**Comment by yuansx** [comment]
都有的

**Comment by jianhuihi** [comment]
业务类的没有呀

**Comment by JSFiend** [comment]
有的， 请提供更多信息
