### ISSUE TITLE
扩容失败

### ISSUE THREAD

**Issue by tangj1992** [TarsCloud/TarsWeb#52]
将一个服务扩容到另一台机器上后，将这个服务下线，然后再扩容到同一台机器上就会报错，请问怎么解决

**Comment by ruanshudong** [comment]
啥错误啊?贴一下错误?

**Comment by tangj1992** [comment]
页面提示：系统内部错误

错误日志：

{"level":"error","message":"192.168.88.3|admin|ExpandServerController.js:133|[expandServerPreview] Error: SequelizeUniqueConstraintError: Validation error\n    at Object.ExpandService.expand (/usr/local/tarsweb/app/service/expand/ExpandService.js:191:15)\n    at <anonymous>  ","timestamp":"2020-04-03 09:48:15.411"}

**Comment by zouchengzhuo** [comment]
@tangj1992 能否贴一下package.json里边的版本，看看最新版本是否还存在这个问题。
或者提供step by step的操作步骤？ 这边试了多种方式没有复现，可能是问题描述中“这个”、“同一台”理解有歧义。

**Comment by tangj1992** [comment]
package.json：

{
  "name": "Tars",
  "version": "0.1.1",
  "private": true,
  "scripts": {
    "start": "node server/bin/www",
    "dev": "./node_modules/.bin/nodemon bin/www",
    "prd": "pm2 start bin/www --name=tars-node-web",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@tars/rpc": "*",
    "@tars/stream": "*",
    "callsite": "^1.0.0",
    "cluster": "^0.7.7",
    "debug": "^2.6.3",
    "eslint": "^4.19.1",
    "fs-extra": "^5.0.0",
    "install": "^0.11.0",
    "internal-ip": "^3.0.1",
    "kafka-node": "^2.6.1",
    "koa": "^2.5.1",
    "koa-bodyparser": "^3.2.0",
    "koa-compress": "^2.0.0",
    "koa-convert": "^1.2.0",
    "koa-helmet": "^4.0.0",
    "koa-json": "^2.0.2",
    "koa-limit": "^1.0.2",
    "koa-logger": "^2.0.1",
    "koa-multer": "^1.0.2",
    "koa-onerror": "^1.2.1",
    "koa-router": "^7.1.1",
    "koa-send": "^4.1.0",
    "koa-static": "^4.0.3",
    "koa-views": "^5.2.1",
    "lodash": "^4.17.10",
    "md5-file": "^4.0.0",
    "moment": "^2.22.0",
    "mysql": "^2.15.0",
    "mysql2": "^1.5.1",
    "node-schedule": "^1.3.0",
    "node-ssh": "^5.1.1",
    "request": "^2.87.0",
    "request-promise-any": "^1.0.5",
    "sequelize": "^4.37.10",
    "url": "^0.11.0",
    "validator": "^9.4.1",
    "winston": "^2.4.2",
    "winston-daily-rotate-file": "^1.7.2",
    "yami-sso-client": "^1.0.1"
  },
  "devDependencies": {
    "nodemon": "^1.17.5"
  }
}

**Comment by tangj1992** [comment]
![image](https://user-images.githubusercontent.com/13653933/79929179-94c2f200-8477-11ea-8e45-5e4d2464da70.png)

之前在192.168.8.82上部署过gateway服务，后来下线了，现在再次扩容到192.168.8.82这台机器上时就报系统内部错误

**Comment by zouchengzhuo** [comment]
@tangj1992 0.1.1这个应该是最老的版本了， 你的tars framework框架应该是v1.x的，把TarsWeb项目1.5.1这个tag拉下来，更新一下web服务，试一下吧。

**Comment by tangj1992** [comment]
升级到新版解决了，感谢
