### ISSUE TITLE
接口测试报错

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/TarsWeb#55]
struct TA
{
    0   optional    string      extra = "{}";                       // 附加参数
    1   optional    string      create_at = "1001-01-01 00:00:00";  // 订阅时间
};
接口测试上传tars文件时，如果字段设置了默认值，会报错，去掉默认值就ok了，麻烦看下~

**Comment by zouchengzhuo** [comment]
协议解析时string字段默认值解析某些情况下有bug，已修复
