### ISSUE TITLE
用于保存接口测试的tars文件内容的db字段长度不够用

### ISSUE THREAD

**Issue by pingfang-tx** [TarsCloud/TarsWeb#56]
db_tars_web.t_tars_files表的context字段（用于保存接口测试的tars文件内容），类型为TEXT，最大只支持64K，可否改为MEDIUMTEXT

**Comment by pingfang-tx** [comment]
{"level":"error","message":"10.40.154.58|leonardoliu|InfTestController.js:87|[uploadTarsFile]: SequelizeDatabaseError: Data too long for column 'context' at row 1\n    at Query.formatError (/data/app/web/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)\n    at Execute.handler [as onResult] (/data/app/web/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)\n    at Execute.execute (/data/app/web/node_modules/mysql2/lib/commands/command.js:30:14)\n    at Connection.handlePacket (/data/app/web/node_modules/mysql2/lib/connection.js:408:32)\n    at PacketParser.onPacket (/data/app/web/node_modules/mysql2/lib/connection.js:70:12)\n    at PacketParser.executeStart (/data/app/web/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/data/app/web/node_modules/mysql2/lib/connection.js:77:25)\n    at Socket.emit (events.js:210:5)\n    at addChunk (_stream_readable.js:308:12)\n    at readableAddChunk (_stream_readable.js:289:11)\n    at Socket.Readable.push (_stream_readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)  ","timestamp":"2020-05-18 14:54:54.315"}

**Comment by ruanshudong** [comment]
先得master 和 release/2.4已经修改了, 启动时会自动更新表结构, 改成medium text, 可以更新试一试
