### ISSUE TITLE
创建DCache应用时，提示“Where paramter id has invalid undefined value"

### ISSUE THREAD

**Issue by juffson** [TarsCloud/TarsWeb#80]
TarsWeb有个报错：
{"level":"error","message":"controller.js:392|[saveRouterProxy]: Error: WHERE parameter \"id\" has invalid \"undefined\" value\n    at MySQLQueryGenerator.whereItemQuery (/usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:13)\n    at /usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25\n    at Array.forEach (<anonymous>)\n    at MySQLQueryGenerator.whereItemsQuery (/usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)\n    at MySQLQueryGenerator.whereQuery (/usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2144:24)\n    at MySQLQueryGenerator.updateQuery (/usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/dialects/abstract/query-generator.js:435:116)\n    at QueryInterface.bulkUpdate (/usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/query-interface.js:1043:37)\n    at /usr/local/tars/cpp/deploy/web/node_modules/sequelize/lib/model.js:3226:34\n    at tryCatcher (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/tars/cpp/deploy/web/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:439:21) ","timestamp":"2020-08-25 16:47:20.505"}

![创建弹窗](https://user-images.githubusercontent.com/12583828/91154129-b1a45600-e6f3-11ea-8a1e-90139b327636.jpg)
![应用配置出错](https://user-images.githubusercontent.com/12583828/91154131-b36e1980-e6f3-11ea-9dfd-eb3396c48c7e.jpg)

**Comment by ruanshudong** [comment]
是不是老系统升级上来的?

**Comment by juffson** [comment]
docker发布，更新了DCache和最新的镜像已经修复了；谢谢。
