### ISSUE TITLE
如何修改重定向登录页面的域名？

### ISSUE THREAD

**Issue by huanghantao** [TarsCloud/TarsWeb#82]
我是通过文档的`docker-compose.yml`在服务器上面进行部署的，但是当我访问首页的时候，例如：

```bash
tars-web.dev.com
```

会重定向到登录页面：

```bash
127.0.0.1:3001
```

我希望重定向到：

```bash
tars-web.dev.com:3001
```

**Comment by ruanshudong** [comment]
可以采用最新的版本, 默认只会开一个3000端口了,  docker用v2.4.11版本

**Comment by huanghantao** [comment]
> 可以采用最新的版本, 默认只会开一个3000端口了, docker用v2.4.11版本

👌
