### ISSUE TITLE
扩容时报错

### ISSUE THREAD

**Issue by Neil-Tz** [TarsCloud/TarsWeb#86]
我在扩容时启用了set，set_group有做修改，之后扩容有报错。这样做是不允许的吗？
![be740c3e0906a29a7b000a3a5c19d23](https://user-images.githubusercontent.com/10428412/93841007-dc6ad580-fcc4-11ea-807c-36374cef50b7.png)
![66cf48e14e3a4f54d664217432e8b73](https://user-images.githubusercontent.com/10428412/93841010-de349900-fcc4-11ea-87e9-2d92f0cb034e.png)

**Comment by ruanshudong** [comment]
应该有bug, 我们先看看

**Comment by ruanshudong** [comment]
应该修复了这个问题, 使用最新版本试一试
